before_install:
   - gem install cocoapods
install: 
   - brew update && brew upgrade swiftlint
   - pod install  
language: swift
xcode_project: Rinder.xcodeproj
osx_image: xcode12
xcode_scheme: Rinder
xcode_destination: platform=iOS Simulator,OS=14.1,name=iPhone 12
script:
   - swiftlint 
   - xcodebuild test -workspace 'Rinder.xcworkspace' -scheme 'Rinder' -destination 'platform=iOS Simulator,OS=14.1,name=iPhone 12'
