before_install:
   - gem install cocoapods
install: 
   - brew update && brew upgrade swiftlint
   - pod install  
language: swift
xcode_project: Rinder.xcodeproj
osx_image: xcode12
xcode_scheme: Rinder
xcode_destination: platform=iOS Simulator,OS=14.0,name=iPhone 11
script:
   - swiftlint 
   - xcodebuild test -workspace 'Rinder.xcworkspace' -scheme 'Rinder' -destination 'platform=iOS Simulator,OS=14.0,name=iPhone 11'
after_success:
   - bash <(curl -s https://codecov.io/bash) 
